---
title: "Tips to prepare code without data at hand"
author: "Aleksandra & Clementine"
date: "`r Sys.Date()`"
output: revealjs::revealjs_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load packages -----------------------------------------------------------

# Package names
packages <- c( "data.table", "here", "tidyverse", "highcharter", "data.table","revealjs")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Provide a source file  -----------------------------------------------------------
source(here('scripts', 'tips.R'))
```


# Preapre your project

# Use relative paths

- Bullet 1
- Bullet 2
- Bullet 3

# Read the documentation  

```{r cars, echo = TRUE}
summary(cars)
```

## ... and make use of it


# Read the data and metadata

```{r pressure}
plot(pressure)
```

# Create functions 

to apply on entire dataset or data parts

# Make use of lapply/apply 

# Prepare for data vises

# When you get the data ...

# Example : CBS data 

# Discussion